library('vegan')
library('NHANES')
library('tidyverse')
require(Lock5withR)
library('fivethirtyeight')
library('okcupiddata')
library('lsr')
library('supernova')
library('lme4')
library('magrittr')
library('car')
library('multcomp')
library('emmeans')
library('grid')
library('Hmisc')
library('see')
library('ggExtra')
library('ggpubr')
library('broom')
library('fivethirtyeightdata')
library('dslabs')
library('mosaic')

print('loaded all packages')